In [1]:
# Jersey City Citibike Program 2019 - get 2019May-July tripdata
import pandas as pd
import datetime
import numpy as np
import os

In [2]:
# Get Jersey City Citibike tripdata csv files from 201901 to 201907
filepath1 = os.path.join("Resources" ,"JC-201901-citibike-tripdata.csv")
filepath2 = os.path.join("Resources" ,"JC-201902-citibike-tripdata.csv")
filepath3 = os.path.join("Resources" ,"JC-201903-citibike-tripdata.csv")
filepath4 = os.path.join("Resources" ,"JC-201904-citibike-tripdata.csv")
filepath5 = os.path.join("Resources" ,"JC-201905-citibike-tripdata.csv")
filepath6 = os.path.join("Resources" ,"JC-201906-citibike-tripdata.csv")
filepath7 = os.path.join("Resources" ,"JC-201907-citibike-tripdata.csv")

JCbike_201901 = pd.read_csv(filepath1)
JCbike_201902 = pd.read_csv(filepath2)
JCbike_201903 = pd.read_csv(filepath3)
JCbike_201904 = pd.read_csv(filepath4)
JCbike_201905 = pd.read_csv(filepath5)
JCbike_201906 = pd.read_csv(filepath6)
JCbike_201907 = pd.read_csv(filepath7)

In [3]:
JCbike_201901.head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0

In [4]:
JCbike_2019all = pd.concat([JCbike_201901,JCbike_201902,JCbike_201903,JCbike_201904,JCbike_201905,JCbike_201906,JCbike_201907])

In [5]:
JCbike_2019all.count()

tripduration               214214
starttime                  214214
stoptime                   214214
start station id           214214
start station name         214214
start station latitude     214214
start station longitude    214214
end station id             214214
end station name           214214
end station latitude       214214
end station longitude      214214
bikeid                     214214
usertype                   214214
birth year                 214214
gender                     214214
dtype: int64

In [6]:
filepath2019= os.path.join("Resources" ,"JCbike_2019all.csv")
JCbike_2019all.to_csv(filepath2019,index=False)
JCbike_2019all.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,201,2019-01-01 03:09:09.7110,2019-01-01 03:12:30.8790,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,29612,Subscriber,1993,1
1,505,2019-01-01 05:18:00.1060,2019-01-01 05:26:25.9050,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29213,Subscriber,1972,2
2,756,2019-01-01 10:36:33.3400,2019-01-01 10:49:10.2600,3183,Exchange Place,40.716247,-74.033459,3192,Liberty Light Rail,40.711242,-74.055701,26164,Subscriber,1985,1
3,1575,2019-01-01 12:43:38.6430,2019-01-01 13:09:54.5280,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29672,Customer,1969,0
4,1566,2019-01-01 12:43:39.6010,2019-01-01 13:09:46.5100,3183,Exchange Place,40.716247,-74.033459,3638,Washington St,40.724294,-74.035483,29522,Customer,1969,0